# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.


stages:
  - build_image
  - lint
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

# Build i push obrazu
build_ci_image:
  stage: build_image
  image: docker:20.10
  services:
    - docker:dind
  script:
    - echo "Logging into GitLab Container Registry..."
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:wchat-ci-latest -f Dockerfile.ci .
    - docker push $CI_REGISTRY_IMAGE:wchat-ci-latest
  only:
    - master

# Szablon dla jobów
.image_ci:
  image: $CI_REGISTRY_IMAGE:wchat-ci-latest
  before_script:
    - echo "Logging into GitLab Container Registry..."
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

clang_check:
  stage: lint
  extends: .image_ci
  script:
    - make clang-check
  allow_failure: true

cpplint:
  stage: lint
  extends: .image_ci
  script:
    - make cpplint
  allow_failure: true

build_app:
  stage: build
  extends: .image_ci
  script:
    - make compile
