# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.

stages:
  - build_image
  - lint
  - build
  - test

# Krok 1: budowa obrazu
build_ci_image:
  stage: build_image
  image: docker:20.10 # używamy Dockera zainstalowanego
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker build -t my-ci-image -f Dockerfile.ci .
    - docker save my-ci-image | gzip > my-ci-image.tar.gz
  artifacts:
    paths:
      - my-ci-image.tar.gz
    expire_in: 1h

# Helper: wczytanie obrazu
.load_ci_image:
  before_script:
    - docker load -i my-ci-image.tar.gz

clang_check:
  stage: lint
  image: docker:20.10
  services: [docker:dind]
  extends: .load_ci_image
  script:
    - docker run --rm -v $CI_PROJECT_DIR:/app -w /app my-ci-image make clang-check
  allow_failure: true

cpplint:
  stage: lint
  image: docker:20.10
  services: [docker:dind]
  extends: .load_ci_image
  script:
    - docker run --rm -v $CI_PROJECT_DIR:/app -w /app my-ci-image make cpplint
  allow_failure: true

build_app:
  stage: build
  image: docker:20.10
  services: [docker:dind]
  extends: .load_ci_image
  script:
    - docker run --rm -v $CI_PROJECT_DIR:/app -w /app my-ci-image make compile
