# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.

stages:
  - build_image
  - lint
  - build
  - test

# Krok 1: budowa obrazu
build_ci_image:
  stage: build_image
  image: docker:20.10 # używamy Dockera zainstalowanego
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker build -t wchat-ci-image -f Dockerfile.ci .

clang_check:
  stage: lint
  image: wchat-ci-image:latest
  script:
    - make clang-check
  allow_failure: true

cpplint:
  stage: lint
  image: wchat-ci-image:latest
  script:
    - make cpplint
  allow_failure: true

build_app:
cpplint:
  stage: lint
  image: wchat-ci-image:latest
  script:
    - make compile
